from Model import Model

class Instrument(Model):
    def __init__(self, options={}):
        Model.__init__(self, options)
    
    def props(self):
        return [
            "Ar",
            "Av",
            "Beta",
            "Bvps",
            "Ch",
            "Chp",
            "Cmp",
            "Country",
            "CrntRt",
            "CshFlEstmt",
            "De",
            "Dh",
            "DiffYhDh",
            "DiffYlDl",
            "Dl",
            "DlEPS3YrGrth",
            "E1",
            "E2",
            "EbitEstmt",
            "Eps",
            "EpsEsmt",
            "Eqsm",
            "ExSn",
            "FpEPS",
            "FrNm",
            "Grm",
            "Ind",
            "It",
            "Mc",
            "MstarGrRt",
            "MstarPrftRt",
            "NetIncome5YrAvg",
            "NetMrgnIndexCmpr",
            "NetMrgnIndexDiff",
            "NiLQr",
            "NiLYr",
            "Nmp",
            "NtIn1YrGr",
            "NtIncmGrthRt",
            "Opm",
            "Opn",
            "OprtCF",
            "PEIndexCmpr",
            "PEIndexDiff",
            "Pe",
            "Pp",
            "PrCh1Mo",
            "PrCh3Mo",
            "PrCh6Mo",
            "PrCshfl",
            "PtB",
            "PtS",
            "PytRt",
            "QckRt",
            "ROEIndexCmpr",
            "ROEIndexDiff",
            "Re1YrGr",
            "Re3Yr",
            "Re5Yr",
            "ReLQr",
            "ReLYr",
            "Roa",
            "Roe",
            "RtCap",
            "Sales5YrAvg",
            "Sec",
            "SlsGrthRt",
            "St",
            "StkStyl",
            "StkTyp",
            "Sym",
            "Typ",
            "V",
            "VolumeSurge",
            "Yh",
            "Yl",
            "YrPrTgt",
            "eqType",
            "instrument",
            "marketCapCat",
            "mkt",
            "shrsOs"
        ]

